spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    default-property-inclusion: non_null
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mall_cloud?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
